name: Voice Smoke
on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  voice-smoke:
    runs-on: windows-latest
    timeout-minutes: 10
    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      PORT: 3001
      API_BASE: http://localhost:3001
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - run: npm ci
      - run: npm run build
      - name: start backend
        run: |
          Start-Process -NoNewWindow node "dist\backend\server.js"
          Start-Sleep -Seconds 5
      - name: probe voice
        run: powershell -ExecutionPolicy Bypass -File .\voice-probe.ps1 -Base http://localhost:3001 -Audio .\fixtures\hello_luna.wav
